// openapi-ts.config.ts — codegen config for the Aura REST client.
//
// Regenerate with:  npm run codegen   (or `task codegen` from the repo root)
//
// Input  : openapi/openapi.yaml   (the Aura API spec, OpenAPI 3.1)
// Output : src/generated/         (typed client generated by @hey-api/openapi-ts,
//                                 one typed function per operationId). The
//                                 generated tree is COMMITTED (not gitignored)
//                                 so end users who `pi install` this package
//                                 get a working client without running codegen.
//
// We use @hey-api/openapi-ts@0.99.x. A bare string `input: "openapi/openapi.yaml"`
// is ambiguous in 0.99 — the parser sees `org/project`-shaped text and tries
// to resolve it as a Hey API platform registry shorthand. A leading `./`
// forces file-path interpretation (the parser only routes `org/project`-shaped
// strings through the shorthand resolver).
//
// In the 0.99 plugin model the HTTP client is itself a plugin, so we list it
// explicitly alongside the default @hey-api/typescript + @hey-api/sdk plugins
// (when you set `plugins`, the defaults are no longer added automatically).

import { defineConfig } from "@hey-api/openapi-ts";

export default defineConfig({
  input: "./openapi/openapi.yaml",
  output: "src/generated",
  plugins: [
    // TypeScript interfaces for every component schema + request/response.
    "@hey-api/typescript",
    // One typed function per operationId (tree-shakeable, function-based).
    "@hey-api/sdk",
    // Native-fetch HTTP client the SDK functions call into.
    "@hey-api/client-fetch",
  ],
});
